# Generated by Django 5.1.7 on 2025-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('url', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
